#!/usr/bin/env sh
DIR=`pwd`
cd $DIR
git submodule init
git submodule update
rm -rf ~/.vimrc
rm -rf ~/.gitconfig
rm -rf ~/.vim
rm -rf ~/.gitignore
cp -r $DIR/.vimrc ~/
cp -r $DIR/.gitconfig ~/
cp -r $DIR/.vim ~/
cp -r $DIR/.gitignore ~/
sleep 1
vim +PluginInstall +qall
sleep 1
cd ~/.vim/bundle/YouCompleteMe
python install.py
echo 'DONE!'
