#!/usr/bin/env sh
DIR=`pwd`
cd $DIR
git submodule init
git submodule update
rm -rf ~/.vimrc
rm -rf ~/.gitconfig
rm -rf ~/.vim
cp -r $DIR/.vimrc ~/
cp -r $DIR/.gitconfig ~/
cp -r $DIR/.vim ~/
sleep 1
vim +BundleInstall +qall
