return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	opts = {
		ensure_installed = {
			"awk",
			"bash",
			"c",
			"c_sharp",
			"cmake",
			"comment",
			"cpp",
			"css",
			"csv",
			"desktop",
			"diff",
			"dockerfile",
			"editorconfig",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"goctl",
			"gomod",
			"gosum",
			"gotmpl",
			"gowork",
			"gpg",
			"graphql",
			"html",
			"http",
			"ini",
			"jinja",
			"jq",
			"just",
			"llvm",
			"make",
			"markdown",
			"nginx",
			"passwd",
			"proto",
			"python",
			"regex",
			"sql",
			"ssh_config",
			"templ",
			"terraform",
			"udev",
			"vim",
			"vimdoc",
			"yaml",
			"zig",
			"lua",
			"query",
			"elixir",
			"heex",
			"javascript",
			"html",
			"go",
		},
		auto_install = true,
		sync_install = false,
		highlight = { enable = true },
		indent = { enable = true },
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "<Enter>", -- set to `false` to disable one of the mappings
				node_incremental = "<Enter>",
				scope_incremental = false,
				node_decremental = "<Backspace>",
			},
		},
	},
}
